### ISSUE TITLE
agnostic setting

### ISSUE THREAD

**Issue by wangchust** [ksaito-ut/openworld_ldet#1]
Hi, I have two simple questions.
1. How to set config file when train plain maskrcnn in an agnostic way.
2. why set num_classes to 80 under VOC to NonVOC setting.

**Comment by wangchust** [comment]
By the way, the link of maskrcnn trained weights seems to be ldet model. Because it get the same scores as ldet gets in paper

**Comment by ksaito-ut** [comment]
Thanks for reporting the issue on the mask rcnn trained model. I will look into the issue. 

1. First, you should set the number of class as 1 in your config. Also, in the training script, i.e., trainer_plain.py, you need to set the classes of instances as 1, like
`for da in data: 
       da['instances'].gt_classes = da['instances'].gt_classes * 0` in line 141. 

2. It is just because we kept the class index of COCO. We just avoided mapping the classes to that of 20. I guess it will not make a large difference in the performance.

**Comment by wangchust** [comment]
Thank you for your reply. I'll close this issue
